### ISSUE TITLE
Confirmed cases in France in 04-14 are less than in 04-13

### ISSUE THREAD

**Issue by LoretoSanchez** [CSSEGISandData/COVID-19#2246]
I just found that confirmed cases in France on 04-14 are about 5000 cases less than on 04-13.

**Comment by gbhgit** [comment]
hi, i found the same problem

**Comment by PavelGorbanj** [comment]
it's a duplicate that was already discussed in 2226

**Comment by Aureuum** [comment]
@LoretoSanchez Yes, the time series data for France since 4/4 are in large excess (about 20k-30k) compared to the correct official data. The probable cause is that the jhu.edu site itself shows the wrong data, and then everybody copies it.

**Comment by mendes-jom** [comment]
Thanks a lot  for your intervention.
Merci beaucoup
Muito Obrigado
![Chart8_16-04-2020](https://user-images.githubusercontent.com/47787853/79495206-2a93f280-801c-11ea-8123-e72b6661a94c.jpg)

**Comment by mendes-jom** [comment]
And Cases  by Mio  better too.   
![Chart6_16-04-2020](https://user-images.githubusercontent.com/47787853/79495625-c887bd00-801c-11ea-9a86-e287585d9204.jpg)
Thanks again

**Comment by Aureuum** [comment]
Since they don't seem to fix it, you can just replace your data with this:
4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20
56989,59105,64338,68605,70478,74390,78167,82048,86334,90676,93790,95403,98076,103573,106206

**Comment by boogheta** [comment]
it was fixed earlier tonight! Thanks @CSSEGISandData !

**Comment by MelbourneDeveloper** [comment]
@Aureuum where do those replacement values come from?

**Comment by Aureuum** [comment]
@MelbourneDeveloper They come from here:
https://github.com/opencovid19-fr/data/tree/master/ministere-sante
and here:
https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_France

**Comment by Aureuum** [comment]
@boogheta Yes, they fixed several of the values for France, but the 4 last, for 4/12-4/15, are still wrong.

**Comment by LoretoSanchez** [comment]
Thank you so much  for the replies!

**Comment by MelbourneDeveloper** [comment]
@Aureuum, @LoretoSanchez  have a look at this [colossal mistake](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv#L3189)

  | French Polynesia | France | 2020-03-23 23:19:21 | -17.6797 | -149.4068 | 19874 | 860 | 2200 | 16814 | French Polynesia, France
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Again, I picked this up using my database tool. I can show people how to use it to find these anomalies.

https://github.com/MelbourneDeveloper/COVID-19-DB

**Comment by Aureuum** [comment]
@MelbourneDeveloper Yes, big error for sure! 
The time series says Fr.Pol. has 55 total cases (but haven't checked that against the official).
And thanks for sharing your database tool! :)

**Comment by MelbourneDeveloper** [comment]
@Aureuum I would love to help automating the process of validating the data

**Comment by Aureuum** [comment]
@MelbourneDeveloper Thanks! :)

**Comment by RouxRC** [comment]
@Aureuum They explain why in #2094. Starting from April 12th, they include both confirmed cases and suspected cases from nursing homes, which are not supposed to overlap anymore since France now reports 2 different figures from these.

**Comment by MelbourneDeveloper** [comment]
@RouxRC shouldn't data be revised from before that time? 

If data is not revised, it's impossible to do calculations over time and time-based modeling is next to impossible.

**Comment by RouxRC** [comment]
I agree, but the data does not exist so far, this is not @CSSEGISandData's responsability until such data is actually released by France for this period (which i fear will probably never come). Although IMHO what we could discuss is the choice of including suspected cases in an indicator named "confirmed", which for most other countries only account for actual positive tests.

**Comment by MelbourneDeveloper** [comment]
@RouxRC the column is already called "Confirmed". What I suggest is a "Suspected" column. That would work well because it would allow any country that is recording suspected cases to add data there.

**Comment by Aureuum** [comment]
I also think it's important to be able to compare countries on equal terms, so we would at least have a dataset for FR as well with just confirmed cases.

**Comment by MelbourneDeveloper** [comment]
@Aureuum true, but the point is the column is called _Confirmed_. _Suspected_ cases have no business being in a column called _Confirmed_.

**Comment by Aureuum** [comment]
And thanks @RouxRC for the clarification! :)

**Comment by Aureuum** [comment]
@MelbourneDeveloper Yes of course, that's important to avoid any confusion.

**Comment by MelbourneDeveloper** [comment]
@Aureuum @RouxRC here is a comprehensive list of all the places where the count is revised down:

https://github.com/CSSEGISandData/COVID-19/issues/2256

There are some very big discrepancies and someone should work on fixing this. At the very least, there should be a comment to note why there is a discrepancy.

**Comment by Aureuum** [comment]
@MelbourneDeveloper Thanks for providing this list! Yes, that would be appropriate with explanations.

**Comment by MelbourneDeveloper** [comment]
@Aureuum very happy to be of service. Can you point to other kinds of discrepancies that need validation?

**Comment by Aureuum** [comment]
@MelbourneDeveloper 
Thank you. 
I'm not aware of any other at this moment.

**Comment by cipriancraciun** [comment]
I have reported this a few days ago on https://github.com/CSSEGISandData/COVID-19/issues/2094#issuecomment-611744632

And although they've closed that issue, the France / French Polynesia numbers are still wrong.
